class Enum {
  static const INTERVALS = [
    "2m",
    "2M",
    "3m",
    "3M",
    "4J",
    "5J",
    "6m",
    "6M",
    "7m",
    "7M",
    "8J",
  ];


  static const NATURAL_NOTES = [
    "C",
    "D",
    "E",
    "F",
    "G",
    "A",
    "B"
  ];

  static const NOTES = [
    "C",
    "C#",
    "Cb",
    "D",
    "D#",
    "Db",
    "E",
    "E#",
    "Eb",
    "F",
    "F#",
    "Fb",
    "G",
    "G#",
    "Gb",
    "A",
    "A#",
    "Ab",
    "B",
    "B#",
    "Bb"
  ];

  static Map<String,Map<String,String>> INTERVAL_NOTES = {
    "C" : {
      "2m": "Db",
      "2M": "D",
      "3m": "Eb",
      "3M": "E",
      "4J": "F",
      "5J": "G",
      "6m": "Ab",
      "6M": "A",
      "7m": "Bb",
      "7M": "B",
      "8J": "C",
    },
    "D" : {
      "2m": "Eb",
      "2M": "E",
      "3m": "F",
      "3M": "F#",
      "4J": "G",
      "5J": "A",
      "6m": "Bb",
      "6M": "B",
      "7m": "C",
      "7M": "C#",
      "8J": "D",
    },
    "E" : {
      "2m": "F",
      "2M": "F#",
      "3m": "G",
      "3M": "G#",
      "4J": "A",
      "5J": "B",
      "6m": "C",
      "6M": "C#",
      "7m": "D",
      "7M": "D#",
      "8J": "E",
    },
    "F" : {
      "2m": "Gb",
      "2M": "G",
      "3m": "Ab",
      "3M": "A",
      "4J": "Bb",
      "5J": "C",
      "6m": "Db",
      "6M": "D",
      "7m": "Eb",
      "7M": "E",
      "8J": "F",
    },
    "G" : {
      "2m": "Ab",
      "2M": "A",
      "3m": "Bb",
      "3M": "B",
      "4J": "C",
      "5J": "D",
      "6m": "Eb",
      "6M": "E",
      "7m": "F",
      "7M": "F#",
      "8J": "G",
    },
    "A" : {
      "2m": "Bb",
      "2M": "B",
      "3m": "C",
      "3M": "C#",
      "4J": "D",
      "5J": "E",
      "6m": "F",
      "6M": "F#",
      "7m": "G",
      "7M": "G#",
      "8J": "A",
    },
    "B" : {
      "2m": "C",
      "2M": "C#",
      "3m": "D",
      "3M": "D#",
      "4J": "E",
      "5J": "F#",
      "6m": "G",
      "6M": "G#",
      "7m": "A",
      "7M": "A#",
      "8J": "B",
    },
  };

}